import Head from 'next/head'
import { Inter } from 'next/font/google'
import Header from './components/Header'
import Firstpage from './components/Firstpage'
import Secondpage from './components/Secondpage'
import Thirdpage from './components/Thirdpage'
import Fourthpage from './components/Fourthpage'
import Fifthpage from './components/Fifthpage'
import Contact from './components/Contact'
import Footer from './components/Footer'
import News from './components/News'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Ensome Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header></Header>
      <Firstpage></Firstpage>
      <Secondpage></Secondpage>
      <Thirdpage></Thirdpage>
      <Fourthpage></Fourthpage>
      <Fifthpage></Fifthpage>
      <Contact></Contact>
      <News></News>
      <Footer/>
    </>
  )
}
